### PR TITLE
Additional spans challenge

### PR DESCRIPTION
**Pull request by benmarch**
@caitlindev, your code from the row span challenge looks good, but there is a subtle bug. I've added one more data sample here to see if you can spot and fix it. Try to think about additional edge cases and add defensive code (and comments) as you are solving this one, and take note of code formatting and styles.

### CODE REVIEW

**Comment by caitlindev** [comment]
> @caitlindev, your code from the row span challenge looks good, but there is a subtle bug. I've added one more data sample here to see if you can spot and fix it. Try to think about additional edge cases and add defensive code (and comments) as you are solving this one, and take note of code formatting and styles.

Hey Ben, a few hours ago I pushed a fix to the bug in question, and now all 3 files of data that I've used in this code test so far are parsing nicely. I also cleaned up inconsistent styles, like the spacing between operands and operators to match the ones in your code. As for handling edge cases, besides checking that values are defined, I'm wondering how much you want to see. For example, adding to the rowSpan or colSpan of a cell in the json file, if there's a widow cell in it's own row then the CSS Grid styles break, and I think fixing them might be better handled where they're being applied rather than in my little `// --------- WRITE CODE HERE ----------` section. I'm more than happy to show you anything else you'd like to see, but I thought I should get more clarification before proceeding.
Looking forward to your feedback Ben, thank you!

**Comment by benmarch** [comment]
@caitlindev, I have a few questions for you: 

Looking at these lines: https://github.com/caitlindev/hbp/blob/caitlin-smith-code-challenge/src/Grid.jsx#L65-L67
```js
if (gridAreas[pointer[0] + r][pointer[1]]) {
  pointer[1]++
}
```

What happens if `gridAreas[pointer[0] + r][pointer[1]++]` does not exist? That is, what happens if the pointer is already in the last column?

If `r` is greater than `0`, are there any conditions where the conditional will be truthy?

--------

General questions: how did you approach solving this problem? What steps did you take to find a solution?

**Comment by caitlindev** [comment]
@benmarch looking at the code again, I want to run by you a different approach. I increment the column count if the current position is occupied by a previous multi-row cell, but it doesn't check the next position or the position after that and so on. I would put the logic that increments both the column and the row into its own function that takes the `pointer` and `gridAreas` arrays as parameters and returns the next open position. What do you think?

For your other questions:

"How did you approach solving this problem? What steps did you take to find a solution?"
I'd never messed with CSS Grids before this, so I had to read up on that first. I commented out the grid and cell styles at first to see how the data was loading. Then, I took a look at the End Result JSON to see how you were handling data that spanned multiple cells, compared it to the initial imported data, and then worked backwards from there.

**Comment by benmarch** [comment]
@caitlindev, I like your proposal to put the code to find the next available cell in its own function. 

Thanks for sharing your problem-solving approach. Have you tried contriving your own grid(s) on paper to help refine your algorithm? I find that helps me identify edge cases and allows me to articulate the approach before codifying it.

**Comment by caitlindev** [comment]
> @caitlindev, I like your proposal to put the code to find the next available cell in its own function.
> 
> Thanks for sharing your problem-solving approach. Have you tried contriving your own grid(s) on paper to help refine your algorithm? I find that helps me identify edge cases and allows me to articulate the approach before codifying it.

I thought about doing that actually. I'm stuck on a bug tonight that I think I need to sleep on and take another look at tomorrow...hope that's ok with you. I'm doing a recursive function that starts at the current cell's position and loops through each consecutive position after that until it finds one that's vacant and returns the position row and col. It works for the most part, but I'm running into a React error I've not seen before `Uncaught TypeError: Invalid attempt to destructure non-iterable instance`

**Comment by benmarch** [comment]
@caitlindev, sounds good to me. The recursive strategy sounds promising, I hope you get that working.

The error sounds like you might be doing something like this: `const [row, col] = pointer`, but `pointer` is not an array or object for some reason. The error basically means you are doing a destructuring, but the r-value isn't destructurable (i.e., an array or object).

**Comment by benmarch** [comment]
You're really close. The problem is on this line: https://github.com/caitlindev/hbp/blob/caitlin-smith-code-challenge/src/Grid.jsx#L39

**Comment by caitlindev** [comment]
> You're really close. The problem is on this line: https://github.com/caitlindev/hbp/blob/caitlin-smith-code-challenge/src/Grid.jsx#L39

Needed to return it!

**Pull request merged**
